Fix read replica config option
airasia/terraform-google-postgres_db pull request #9
Opened 2023-01-06 05:38 UTC by kulkarnisourabh2

- To fix following error in pipeline https://gitlab.com/airasia-superapp/devops/iac/ecomm-iac/-/jobs/3563335993

``` Error: Invalid value for module argument
  on .terraform/modules/stg_infra.postgres_db/main.tf line 96, in module "google_postgres_db":
  96:   read_replicas = [
  97:     for array_index in range(var.read_replica_count) : {
  98:       name = array_index
  99:       tier = var.instance_size_read_replica
 100:       zone = local.zone_read_replica
 101:       ip_configuration = {
 102:         authorized_networks = local.read_replica_authorized_networks
 103:         ipv4_enabled        = var.public_access_read_replica
 104:         private_network     = var.private_network
 105:         require_ssl         = null
 106:       }
 107:       database_flags  = local.db_flags_read_replica
 108:       disk_autoresize = var.disk_auto_resize_read_replica
 109:       disk_size       = var.disk_size_gb_read_replica
 110:       disk_type       = "PD_SSD"
 111:       user_labels     = var.labels_read_replica
 112:     }
 113:   ]
The given value is not suitable for child module variable "read_replicas"
defined at
.terraform/modules/stg_infra.postgres_db.google_postgres_db/modules/postgresql/variables.tf:174,1-25:
element 0: attribute "encryption_key_name" is required.```

2023-01-06 07:39 UTC, syedrakib requested changes
Need to remove the quotes around `null` for default value.

2023-01-06 07:39 UTC, syedrakib commented on variables.tf
> +  default     = "null"
```suggestion
  description = "Encryption key is required for replicas in different regions. For replicas in same region as master, set encryption_key_name = null"
  type        = string
  default     = null
```

2023-01-06 09:34 UTC, syedrakib reviewed
adding suffix to the var to be consistent with rest of the read_replica vars

2023-01-06 09:34 UTC, syedrakib commented on main.tf
> +      encryption_key_name = var.encryption_key_name
```suggestion
      encryption_key_name = var.encryption_key_name_read_replica
```

2023-01-06 09:34 UTC, syedrakib commented on variables.tf
> +variable "encryption_key_name" {
```suggestion
variable "encryption_key_name_read_replica" {
```

2023-01-06 09:35 UTC, syedrakib approved these changes

2023-01-09 02:17 UTC, prajithparammal approved these changes

2023-01-10 07:22 UTC, merged